name: Production Build

on:
  push:
    branches:
      - 'master'

jobs:
  checkstyle:
    name: Run CheckStyle and Codesmell
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Android Lint
        run: bash ./gradlew lint
      - name: Upload Lint Report
        uses: actions/upload-artifact@v1
        with:
          name: lint report
          path: app/build/reports

      - name: Ktlint
        run: bash ./gradlew ktlint

      - name: Detekt
        run: bash ./gradlew detekt
      - name: Upload Detekt Report
        uses: actions/upload-artifact@v1
        with:
          name: detekt report
          path: build/reports/detekt/

  unit_test:
    name: Run Unit Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Unit tests
        run: bash ./gradlew testDebugUnitTest --stacktrace
      - name: Upload Unit Test Report
        uses: actions/upload-artifact@v1
        with:
          name: unit test report
          path: app/build/reports/tests/testDebugUnitTest/

  instrumentation_test:
    name: Run UI Test
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
      - name: Upload Instrumentation Test Report
        uses: actions/upload-artifact@v1
        with:
          name: intrumentation test report
          path: app/build/reports/androidTests/

  build_apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk